name: Run Pytest

on:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  run-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@10.0.1

      - name: Run pytest
        run: uv run pytest
