name: Run Pytest and Ruff lint+formatting

on:
  pull_request:

permissions:
  contents: read

jobs:
  run-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Run pytest
        run: uv run pytest

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "check"

      - name: Check Ruff formatting
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "format --check"
